// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
    // @ts-ignore
    return window['go']['cmd']['DashboardApp']['GetStatus']();
}

export function GetVersion() {
    // @ts-ignore
    return window['go']['cmd']['DashboardApp']['GetVersion']();
}
